Update Ex_Sortides_Estandard

diff --git a/A_Introducció/Ex_Sortides_Estandard b/A_Introducció/Ex_Sortides_Estandard
--- a/A_Introducció/Ex_Sortides_Estandard
+++ b/A_Introducció/Ex_Sortides_Estandard
@@ -2,32 +2,27 @@
 
 # Script senzill que utilitza stdin, stdout y stderr
 
-echo "Introdueix el teu nom:"  # stdout
+echo "Introdueix el teu nom (o no responguis res):"  # stdout
 # Utilitzem echo per imprimir un missatge en la sortida estàndard (stdout).
 
 read nom  # stdin
 # Utilitzem read per llegir el nom des de l'entrada estàndard (stdin).
 
 if [ -z "$nom" ]; then
-    echo "Error: El nom no pot estar buit." >&2  # stderr
+    echo "Error!! NO has introduiit el teu nom." >&2  # stderr
 # Verifiquem si el nom està buit i emetem un missatge d'error 
 # en la sortida estàndard (stderr) si és el cas.
 
     exit 1
 fi
 
-echo "Hola, $nom. ¡Benvingut!"  # stdout
-
-echo "Aquest és un missatge normal."  # stdout
-
-# Simula un error y emet un missatge a stderr
-echo "Això és un missatge d'error." >&2  # stderr
-
 # >& és la sintaxis per redirigir un flux (stream) a 
 # un altre descriptor d’arxiu (0 és stdin, 1 és stdout i 2 is stderr)
 
-echo "Indique un comando a realizar:"
-read # Probemos de ejecutar un comando que no existe. 
-$REPLY &>> error.txt
+echo " Hola, $nom!! Benvingut!!" #stdout
+
+echo "Per cert, escriu una comanda a executar (o inventa-te-la):"
+read #  
+$REPLY &>> error # Si la comanda no existeix (error), ho guardem en un arxiu
 
 echo "Fi de l'script"
